const contries = [
  { Countries: "Guernsey (GG)", Zone: "zone1" },
  { Countries: "Ireland, Rep. Of (IE)", Zone: "zone1" },
  { Countries: "Jersey (JE)", Zone: "zone1" },
  { Countries: "United Kingdom (GB)", Zone: "zone1" },
  { Countries: "Benin (BJ)", Zone: "zone2" },
  { Countries: "Burkina Faso (BF)", Zone: "zone2" },
  { Countries: "Cameroon (CM)", Zone: "zone2" },
  { Countries: "Cape Verde (CV)", Zone: "zone2" },
  { Countries: "Central African Rep(CF)", Zone: "zone2" },
  { Countries: "Chad (TD)", Zone: "zone2" },
  { Countries: "Congo (CG)", Zone: "zone2" },
  { Countries: "Congo, DPR (CD)", Zone: "zone2" },
  { Countries: "Cote D Ivoire (CI)", Zone: "zone2" },
  { Countries: "Gabon (GA)", Zone: "zone2" },
  { Countries: "Gambia (GM)", Zone: "zone2" },
  { Countries: "Ghana (GH)", Zone: "zone2" },
  { Countries: "Guinea Rep. (GN)", Zone: "zone2" },
  { Countries: "Guinea-Bissau (GW)", Zone: "zone2" },
  { Countries: "Guinea-Equatorial (GQ)", Zone: "zone2" },
  { Countries: "Liberia (LR)", Zone: "zone2" },
  { Countries: "Mali (ML)", Zone: "zone2" },
  { Countries: "Niger (NE)", Zone: "zone2" },
  { Countries: "Sao Tome And Principe (ST)", Zone: "zone2" },
  { Countries: "Senegal (SN)", Zone: "zone2" },
  { Countries: "Sierra Leone (SL)", Zone: "zone2" },
  { Countries: "Togo (TG)", Zone: "zone2" },
  { Countries: "Canada (CA)", Zone: "zone3" },
  { Countries: "Mexico (MX)", Zone: "zone3" },
  { Countries: "USA (US)", Zone: "zone3" },
  { Countries: "Albania (AL)", Zone: "zone4" },
  { Countries: "Andorra (AD)", Zone: "zone4" },
  { Countries: "Austria (AT)", Zone: "zone4" },
  { Countries: "Belarus (BY)", Zone: "zone4" },
  { Countries: "Belgium (BE)", Zone: "zone4" },
  { Countries: "Bosnia & Herzegovina(BA)", Zone: "zone4" },
  { Countries: "Bulgaria (BG)", Zone: "zone4" },
  { Countries: "Canary Islands, The (IC)", Zone: "zone4" },
  { Countries: "Croatia (HR)", Zone: "zone4" },
  { Countries: "Cyprus (CY)", Zone: "zone4" },
  { Countries: "Czech Rep., The (CZ)", Zone: "zone4" },
  { Countries: "Denmark (DK)", Zone: "zone4" },
  { Countries: "Estonia (EE)", Zone: "zone4" },
  { Countries: "Faroe Islands (FO)", Zone: "zone4" },
  { Countries: "Finland (FI)", Zone: "zone4" },
  { Countries: "France (FR)", Zone: "zone4" },
  { Countries: "Germany (DE)", Zone: "zone4" },
  { Countries: "Gibraltar (GI)", Zone: "zone4" },
  { Countries: "Greece (GR)", Zone: "zone4" },
  { Countries: "Greenland (GL)", Zone: "zone4" },
  { Countries: "Hungary (HU)", Zone: "zone4" },
  { Countries: "Iceland (IS)", Zone: "zone4" },
  { Countries: "Italy (IT)", Zone: "zone4" },
  { Countries: "Kosovo (KV)", Zone: "zone4" },
  { Countries: "Latvia (LV)", Zone: "zone4" },
  { Countries: "Liechtenstein (LI)", Zone: "zone4" },
  { Countries: "Lithuania (LT)", Zone: "zone4" },
  { Countries: "Luxembourg (LU)", Zone: "zone4" },
  { Countries: "Malta (MT)", Zone: "zone4" },
  { Countries: "Moldova, Rep. Of (MD)", Zone: "zone4" },
  { Countries: "Monaco (MC)", Zone: "zone4" },
  { Countries: "Montenegro, Rep Of (ME)", Zone: "zone4" },
  { Countries: "Netherlands, The (NL)", Zone: "zone4" },
  { Countries: "North Macedonia (MK)", Zone: "zone4" },
  { Countries: "Norway (NO)", Zone: "zone4" },
  { Countries: "Poland (PL)", Zone: "zone4" },
  { Countries: "Portugal (PT)", Zone: "zone4" },
  { Countries: "Romania (RO)", Zone: "zone4" },
  { Countries: "Russian Federation (RU)", Zone: "zone4" },
  { Countries: "San Marino (SM)", Zone: "zone4" },
  { Countries: "Serbia, Rep. Of (RS)", Zone: "zone4" },
  { Countries: "Slovakia (SK)", Zone: "zone4" },
  { Countries: "Slovenia (SI)", Zone: "zone4" },
  { Countries: "Spain (ES)", Zone: "zone4" },
  { Countries: "Sweden (SE)", Zone: "zone4" },
  { Countries: "Switzerland (CH)", Zone: "zone4" },
  { Countries: "Turkey (TR)", Zone: "zone4" },
  { Countries: "Ukraine (UA)", Zone: "zone4" },
  { Countries: "Vatican City (VA)", Zone: "zone4" },
  { Countries: "Algeria (DZ)", Zone: "zone5" },
  { Countries: "Angola (AO)", Zone: "zone5" },
  { Countries: "Botswana (BW)", Zone: "zone5" },
  { Countries: "Burundi (BI)", Zone: "zone5" },
  { Countries: "Comoros (KM)", Zone: "zone5" },
  { Countries: "Djibouti (DJ)", Zone: "zone5" },
  { Countries: "Egypt (EG)", Zone: "zone5" },
  { Countries: "Eritrea (ER)", Zone: "zone5" },
  { Countries: "Eswatini (SZ)", Zone: "zone5" },
  { Countries: "Ethiopia (ET)", Zone: "zone5" },
  { Countries: "Kenya (KE)", Zone: "zone5" },
  { Countries: "Lesotho (LS)", Zone: "zone5" },
  { Countries: "Libya (LY)", Zone: "zone5" },
  { Countries: "Madagascar (MG)", Zone: "zone5" },
  { Countries: "Malawi (MW)", Zone: "zone5" },
  { Countries: "Mauritania (MR)", Zone: "zone5" },
  { Countries: "Mauritius (MU)", Zone: "zone5" },
  { Countries: "Mayotte (YT)", Zone: "zone5" },
  { Countries: "Morocco (MA)", Zone: "zone5" },
  { Countries: "Mozambique (MZ)", Zone: "zone5" },
  { Countries: "Namibia (NA)", Zone: "zone5" },
  { Countries: "Reunion, Island Of (RE)", Zone: "zone5" },
  { Countries: "Rwanda (RW)", Zone: "zone5" },
  { Countries: "Seychelles (SC)", Zone: "zone5" },
  { Countries: "Somalia (SO)", Zone: "zone5" },
  { Countries: "Somaliland, Rep Of (XS)", Zone: "zone5" },
  { Countries: "South Africa (ZA)", Zone: "zone5" },
  { Countries: "South Sudan (SS)", Zone: "zone5" },
  { Countries: "Sudan (SD)", Zone: "zone5" },
  { Countries: "Tanzania (TZ)", Zone: "zone5" },
  { Countries: "Tunisia (TN)", Zone: "zone5" },
  { Countries: "Uganda (UG)", Zone: "zone5" },
  { Countries: "Zambia (ZM)", Zone: "zone5" },
  { Countries: "Zimbabwe (ZW)", Zone: "zone5" },
  { Countries: "Afghanistan (AF)", Zone: "zone6" },
  { Countries: "Bahrain (BH)", Zone: "zone6" },
  { Countries: "Iran (IR)", Zone: "zone6" },
  { Countries: "Iraq (IQ)", Zone: "zone6" },
  { Countries: "Israel (IL)", Zone: "zone6" },
  { Countries: "Jordan (JO)", Zone: "zone6" },
  { Countries: "Kuwait (KW)", Zone: "zone6" },
  { Countries: "Lebanon (LB)", Zone: "zone6" },
  { Countries: "Oman (OM)", Zone: "zone6" },
  { Countries: "Qatar (QA)", Zone: "zone6" },
  { Countries: "Saudi Arabia (SA)", Zone: "zone6" },
  { Countries: "Syria (SY)", Zone: "zone6" },
  { Countries: "United Arab Emirates (AE)", Zone: "zone6" },
  { Countries: "Yemen, Rep. Of (YE)", Zone: "zone6" },
  { Countries: "Armenia (AM)", Zone: "zone7" },
  { Countries: "Australia (AU)", Zone: "zone7" },
  { Countries: "Azerbaijan (AZ)", Zone: "zone7" },
  { Countries: "Bangladesh (BD)", Zone: "zone7" },
  { Countries: "Bhutan (BT)", Zone: "zone7" },
  { Countries: "Brunei (BN)", Zone: "zone7" },
  { Countries: "Cambodia (KH)", Zone: "zone7" },
  { Countries: "China (CN)", Zone: "zone7" },
  { Countries: "Georgia (GE)", Zone: "zone7" },
  { Countries: "Hong Kong SAR China (HK)", Zone: "zone7" },
  { Countries: "India (IN)", Zone: "zone7" },
  { Countries: "Indonesia (ID)", Zone: "zone7" },
  { Countries: "Japan (JP)", Zone: "zone7" },
  { Countries: "Kazakhstan (KZ)", Zone: "zone7" },
  { Countries: "Korea, Rep. Of (KR)", Zone: "zone7" },
  { Countries: "Korea,  D.P.R Of (KP)", Zone: "zone7" },
  { Countries: "Kyrgyzstan (KG)", Zone: "zone7" },
  { Countries: "Laos (LA)", Zone: "zone7" },
  { Countries: "Macau SAR China (MO)", Zone: "zone7" },
  { Countries: "Malaysia (MY)", Zone: "zone7" },
  { Countries: "Maldives (MV)", Zone: "zone7" },
  { Countries: "Mongolia (MN)", Zone: "zone7" },
  { Countries: "Myanmar (MM)", Zone: "zone7" },
  { Countries: "Nepal (NP)", Zone: "zone7" },
  { Countries: "Pakistan (PK)", Zone: "zone7" },
  { Countries: "Palau (PW)", Zone: "zone7" },
  { Countries: "Philippines, The (PH)", Zone: "zone7" },
  { Countries: "Singapore (SG)", Zone: "zone7" },
  { Countries: "Sri Lanka (LK)", Zone: "zone7" },
  { Countries: "Taiwan (TW)", Zone: "zone7" },
  { Countries: "Tajikistan (TJ)", Zone: "zone7" },
  { Countries: "Thailand (TH)", Zone: "zone7" },
  { Countries: "Timor-Leste (TL)", Zone: "zone7" },
  { Countries: "Turkmenistan (TM)", Zone: "zone7" },
  { Countries: "Uzbekistan (UZ)", Zone: "zone7" },
  { Countries: "Vietnam (VN)", Zone: "zone7" },
  { Countries: "American Samoa (AS)", Zone: "zone8" },
  { Countries: "Anguilla (AI)", Zone: "zone8" },
  { Countries: "Antigua (AG)", Zone: "zone8" },
  { Countries: "Argentina (AR)", Zone: "zone8" },
  { Countries: "Aruba (AW)", Zone: "zone8" },
  { Countries: "Bahamas (BS)", Zone: "zone8" },
  { Countries: "Barbados (BB)", Zone: "zone8" },
  { Countries: "Belize (BZ)", Zone: "zone8" },
  { Countries: "Bermuda (BM)", Zone: "zone8" },
  { Countries: "Bolivia (BO)", Zone: "zone8" },
  { Countries: "Bonaire (XB)", Zone: "zone8" },
  { Countries: "Brazil (BR)", Zone: "zone8" },
  { Countries: "Cayman Islands (KY)", Zone: "zone8" },
  { Countries: "Chile (CL)", Zone: "zone8" },
  { Countries: "Colombia (CO)", Zone: "zone8" },
  { Countries: "Cook Islands (CK)", Zone: "zone8" },
  { Countries: "Costa Rica (CR)", Zone: "zone8" },
  { Countries: "Cuba (CU)", Zone: "zone8" },
  { Countries: "Curacao (XC)", Zone: "zone8" },
  { Countries: "Dominica (DM)", Zone: "zone8" },
  { Countries: "Dominican Rep. (DO)", Zone: "zone8" },
  { Countries: "Ecuador (EC)", Zone: "zone8" },
  { Countries: "El Salvador (SV)", Zone: "zone8" },
  { Countries: "Falkland Islands (FK)", Zone: "zone8" },
  { Countries: "Fiji (FJ)", Zone: "zone8" },
  { Countries: "French Guyana (GF)", Zone: "zone8" },
  { Countries: "Grenada (GD)", Zone: "zone8" },
  { Countries: "Guadeloupe (GP)", Zone: "zone8" },
  { Countries: "Guam (GU)", Zone: "zone8" },
  { Countries: "Guatemala (GT)", Zone: "zone8" },
  { Countries: "Guyana (British) (GY)", Zone: "zone8" },
  { Countries: "Haiti (HT)", Zone: "zone8" },
  { Countries: "Honduras (HN)", Zone: "zone8" },
  { Countries: "Jamaica (JM)", Zone: "zone8" },
  { Countries: "Kiribati (KI)", Zone: "zone8" },
  { Countries: "Mariana Islands (MP)", Zone: "zone8" },
  { Countries: "Marshall Islands (MH)", Zone: "zone8" },
  { Countries: "Martinique (MQ)", Zone: "zone8" },
  { Countries: "Micronesia (FM)", Zone: "zone8" },
  { Countries: "Montserrat (MS)", Zone: "zone8" },
  { Countries: "Nauru, Rep. Of (NR)", Zone: "zone8" },
  { Countries: "Nevis (XN)", Zone: "zone8" },
  { Countries: "New Caledonia (NC)", Zone: "zone8" },
  { Countries: "New Zealand (NZ)", Zone: "zone8" },
  { Countries: "Nicaragua (NI)", Zone: "zone8" },
  { Countries: "Niue (NU)", Zone: "zone8" },
  { Countries: "Panama (PA)", Zone: "zone8" },
  { Countries: "Papua New Guinea (PG)", Zone: "zone8" },
  { Countries: "Paraguay (PY)", Zone: "zone8" },
  { Countries: "Peru (PE)", Zone: "zone8" },
  { Countries: "Puerto Rico (PR)", Zone: "zone8" },
  { Countries: "Saint Helena (SH)", Zone: "zone8" },
  { Countries: "Samoa (WS)", Zone: "zone8" },
  { Countries: "Solomon Islands (SB)", Zone: "zone8" },
  { Countries: "St. Barthelemy (XY)", Zone: "zone8" },
  { Countries: "St. Eustatius (XE)", Zone: "zone8" },
  { Countries: "St. Kitts (KN)", Zone: "zone8" },
  { Countries: "St. Lucia (LC)", Zone: "zone8" },
  { Countries: "St. Maarten (XM)", Zone: "zone8" },
  { Countries: "St. Vincent (VC)", Zone: "zone8" },
  { Countries: "Suriname (SR)", Zone: "zone8" },
  { Countries: "Tahiti (PF)", Zone: "zone8" },
  { Countries: "Tonga (TO)", Zone: "zone8" },
  { Countries: "Trinidad And Tobago (TT)", Zone: "zone8" },
  { Countries: "Turks & Caicos (TC)", Zone: "zone8" },
  { Countries: "Tuvalu (TV)", Zone: "zone8" },
  { Countries: "Uruguay (UY)", Zone: "zone8" },
  { Countries: "Vanuatu (VU)", Zone: "zone8" },
  { Countries: "Venezuela (VE)", Zone: "zone8" },
  { Countries: "Virgin Islands-British (VG)", Zone: "zone8" },
  { Countries: "Virgin Islands-US (VI)", Zone: "zone8" },
];

export default contries;
